--changeset UmeshKumar:Insert-CS-2915

insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','application','auditName','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','businessUnit','businessUnit','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','claimNumber','claimNumber','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','claimDate','claimDate','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','claimAmount','claimAmount','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','claimCurrency','claimCurrency','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','vendorName','vendorName','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','problemType','problemType','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','creditReference','','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','creditReferenceDate','','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','rootCause','rootCauseDescription','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','vendorNumber','vendorNumber','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','invoiceNumber','','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','invoiceDate','','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','paymentNumber','','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','paymentDate','','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','poNumber','','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','narrative','narrative','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','summaryType','Audit','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','auditProject','auditProject','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','clientClaimNumber','clientClaimNumber','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','disposition','disposition','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','stage','stage','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','status','status','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','rootCauseId','rootCauseId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','projectId','projectId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','dispositionId','dispositionId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','stageId','stageId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','statusId','statusId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','vendorId','vendorId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','problemTypeId','problemTypeId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','exchangeRate','exchangeRate','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','appVendorId','appVendorId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIM','templateId','templateId','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','compCd','COMP_CD','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','vendorNumber','VEND_NUM','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','vendorName','VEND_NAME','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','poNumber','PO_NUM','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','invoiceNumber','INV_NUM','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','invoiceDate','INVDATE','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','paymentNumber','CHK_NUM','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','paymentDate','CHKDATE','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','amount','GROSSAMT','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','discount','DISCAMT','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)
insert into [dbo].[ClaimTemplateMapping] (Categeory,Mappingcolumnlabel,MappingExceptionField,CreatedBy,CreatedDate,LastModifiedBy,LastModifiedDate,Deleted) values ('CLAIMDETAILS','netAmount','NETAMT','Prgx',CURRENT_TIMESTAMP,'Prgx',CURRENT_TIMESTAMP,NULL)

--rollback SELECT 1 WHERE 1=0;

--changeset UmeshKumar:Insert-CS-2915-1

update [dbo].[ClaimTemplateMapping]
set Source = 'EXCEPTIONS' where Categeory='CLAIMDETAILS'

--rollback SELECT 1 WHERE 1=0;